version: '3.1'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/data/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  api:
    build: ./api
    volumes:
      - /proc:/proc
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  web:
    build:
      context: ./front
    ports:
      - "80:80"

volumes:
  mysql_data:

