version: '3.1'

services:
  nginx:
    build: 
      context: ./nginx
    image: danielcuque/so1_202112145_p1_nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api
      - web
  db:
    build: 
      context: ./db
    ports:
      - "3306:3306"
    image: danielcuque/so1_202112145_p1_db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto1
  api:
    build: ./api
    volumes:
      - /proc:/proc
    image: danielcuque/so1_202112145_p1_api
    restart: always
    privileged: true
    ports:
      - "8080:8080"
    depends_on:
      - db
  web:
    build:
      context: ./front
    ports:
      - "3000:3000"
    container_name: web
    image: danielcuque/so1_202112145_p1_web

volumes:
  mysql_data:

