version: '3.1'

services:
  db:
    build: 
      context: ./db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/data/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto1
  api:
    build: ./api
    volumes:
      - /proc:/proc
    restart: always
    privileged: true
    ports:
      - "8080:8080"
    depends_on:
      - db
  web:
    build:
      context: ./front
    ports:
      - "80:80"
    container_name: web
    environment:
      - PROXY_IP='http://192.168.1.23'

volumes:
  mysql_data:

