version: '3.1'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/data/db
  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  web:
    build:
      context: ./front
    ports:
      - "80:3000"

volumes:
  mysql_data:

