USE proyecto1;

CREATE TABLE IF NOT EXISTS cpu_state (
    id INT AUTO_INCREMENT PRIMARY KEY,
    value FLOAT NOT NULL,
    date DATE
);

CREATE TABLE IF NOT EXISTS ram_state (
    id INT AUTO_INCREMENT PRIMARY KEY,
    value FLOAT NOT NULL,
    date DATE
);